apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rabbitmq-hpa
  namespace: nathanbenais
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: counter-backend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
